---
title: "R_lesson"
author: "Sandra Tietscher"
date: "4/7/2020"
output: html_document
---

## Load libraries and data

```{r}
library(ggplot2)
library(Seurat)
library(tidyverse)
library(data.table)
library(patchwork)
library(ComplexHeatmap)
library(viridis)
library(scales)

path = "~/Code/10x/10x_Run1_Run2_Pilot_comb/output/"
all.merged <- readRDS(file = paste0(path, "merged_complete_inclCelltype.rds"))

# classify pDCs as myeloid cells for this large overview
ct_levels <- levels(all.merged$cell.type)
ct_levels[7] <- "mast cell/basophil"
ct_levels[9] <- "myeloid"
levels(all.merged$cell.type) <- ct_levels

# Color palette
colors <- hue_pal()(50)
show_col(colors)
```

## Generate UMAP plots

```{r}
out.path = "~/Code/10x/10x_Run1_Run2_Pilot_comb/output/figures_for_paper/Fig1/" 

## reorder patient levels
all.merged$orig.ident <- as.factor(all.merged$orig.ident)
old.levels <- levels(all.merged$orig.ident)
all.merged$orig.ident <- factor(all.merged$orig.ident, levels =  old.levels[c(1,5:9,14, 2:4, 10:13)])

#Subset to very few cells to get small pdfs (for vectorized legends)
cells <- WhichCells(all.merged)
cells.sub <- sample(cells, 100)
object <- subset(all.merged, cells = cells.sub)

#object <- all.merged
  
umap_celltype <- DimPlot(object, group.by = "cell.type", cols = c("#FF5F50", "darkorange2", "gold3", "#77C900", "#00AA5C",  "#00C0BD", "#1F99FF", "#0044DB"))+
  theme_void()

umap_patient <- DimPlot(object, group.by = "orig.ident")+
  theme_void()

umap_TIG <- DimPlot(object, group.by = "TIG")+
  theme_void()

umap_cluster <- DimPlot(all.merged, group.by = "SCT_snn_res.2", label=TRUE)+
  theme_void()

pdf(paste0(out.path, "Fig1_umap_small.pdf"), width = 30, height = 10)
umap_celltype | umap_patient | umap_TIG
dev.off()

png(paste0(out.path, "Fig1_S_umap_patient.png"), width = 25, height = 20, units = "cm", res = 200)
umap_patient
dev.off()

# Highlight fibroblasts
Idents(all.merged) <- all.merged$cell.type
fibroblasts = WhichCells(object = all.merged, ident = c("fibroblast"))
DimPlot(object = all.merged, reduction = 'umap', cells.highlight = fibroblasts, cols.highlight = "#00C1AA", sizes.highlight = 0.7, pt.size = 0.7)

```

## Generate FeaturePlots

```{r}
genes <- c("PTPRC", "PDGFRB", "CD3E", "CD14", "EPCAM", "PECAM1")

#save as png (Illustrator cannot handle UMAPs with lots of cells)
png(paste0(out.path, "Fig1_FeaturePlots.png"), width = 20, height = 30, units = "cm", res = 200)
FeaturePlot(all.merged, genes, max.cutoff = 3) + theme_void()
dev.off()

#save one plot as pdf to get vectorized legend (with very few cells)
cells <- WhichCells(all.merged)
cells.sub <- sample(cells, 1000)
obj.sub <- subset(all.merged, cells = cells.sub)

pdf(paste0(out.path, "Fig1_FeaturePlot_skeleton.pdf"), width = 10, height = 10)
FeaturePlot(obj.sub, "HLA-DRA", max.cutoff = 3)
dev.off()
```

## Generate DotPlots for lineage markers

```{r}

### main cell types only ###

#reorder levels
old.levels <- levels(all.merged$cell.type)
all.merged$cell.type <- factor(all.merged$cell.type, levels =  old.levels[c(6,4,3,1,2,5,7,8)])
Idents(all.merged) <- all.merged$cell.type

genes <- c("EPCAM", "CDH1", "PECAM1", "CAV1", "VWF", "PDGFRB", "FAP", "PTPRC", "CD3E", "NCAM1", "CD14", "HLA-DRA", "ITGAX","MS4A1", "MS4A2",  "IGKC")
genes_PDL1 <- c("CD274", "LAMP3", "CCR7")

pdf(paste0(out.path, "Fig1_dotplot.pdf"), width = 5, height = 4.2)
p <- DotPlot(all.merged, features = c("CD274", "LAMP3", "CCR7"))+
  coord_flip()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())
dev.off()


### all clusters ###
new.levels <- as.character(read.csv(paste0(path, "cluster_celltypes_res2_v2.csv"))[,1])
all.merged$SCT_snn_res.2 <- factor(all.merged$SCT_snn_res.2, levels = new.levels)
Idents(all.merged) <- all.merged$SCT_snn_res.2

p <- DotPlot(all.merged, features = genes_PDL1)+
  coord_flip()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

```

# Gene expression heatmap

```{r}
## Calculate cell type averages
Idents(all.merged) <- all.merged$cell.type
cluster.averages.table <- AverageExpression(object = all.merged, return.seurat = FALSE, assays = "RNA")
RNA.average <- as.matrix(cluster.averages.table[[1]])
#Normalize between 0 and 1
RNA.average.norm <- apply(RNA.average, 1, function(x)(x-min(x))/(max(x)-min(x)))
RNA.average.znorm <- apply(RNA.average, 1, function(x)(x - mean(x)) / sd(x))

T_supp <- c("CD274", "PDCD1LG2", "IDO1", "CD80", "CD86",   "CCL17", "CCL19", "CCL22", "IL15")

p = Heatmap(t(subset(RNA.average.norm, select=T_supp)), show_row_names = TRUE, row_dend_side = "left", heatmap_legend_param = list(title = "Normalized\nmean counts"), col=viridis(100), cluster_rows = FALSE, cluster_columns=FALSE, row_names_side = "left", column_names_side = "top", column_names_rot = 90, column_dend_side = "bottom", row_names_gp = gpar(fontsize = 6), cluster_column_slices = FALSE)
```


