---
title: "Fig2_cluster"
author: "Sandra Tietscher"
date: "4/14/2020"
output: html_document
---

## Load libraries and data

```{r}
library(ggplot2)
library(Seurat)
library(tidyverse)
library(data.table)
library(clustree)
library(magrittr)
library(viridis)
library(patchwork)
library(ComplexHeatmap)

#in.path = "~/Code/10x/10x_Run1_Run2_Pilot_comb/output/TNK_cells/regressed_mito-krt-MGP/"
in.path = "Z://sandrat/Code/10x/10x_Run1_Run2_Pilot_comb/output/TNK_cells/regressed_mito-krt-MGP/"
out.path = "~/Code/10x/10x_Run1_Run2_Pilot_comb/output/figures_for_paper/Fig2/" 

all.Tcell <- readRDS(file=paste0(in.path, 'run1_Tcell_15dim.rds'))
```

# Asssign new cluster names and metacluster identity
Already done when reading in new object.

```{r}
# #Read in table with cluster ids
# cluster.ids <- read.csv(file = paste0(in.path, "metacluster_assignment.csv"))
# 
# #Metacluster assignment
# Idents(all.Tcell) <- all.Tcell$SCT_snn_res.1
# role.ids <- as.character(cluster.ids$metacluster)
# names(role.ids) <- levels(all.Tcell)
# all.Tcell <- RenameIdents(object = all.Tcell, role.ids)
# #Save celltype information in metadata
# all.Tcell[["metacluster"]] <- Idents(object = all.Tcell)
# 
# #New cluster names
# Idents(all.Tcell) <- all.Tcell$SCT_snn_res.1
# new.names <- as.character(cluster.ids$name)
# names(new.names) <- levels(all.Tcell)
# all.Tcell <- RenameIdents(object = all.Tcell, new.names)
# #Save celltype information in metadata
# all.Tcell[["cluster"]] <- Idents(object = all.Tcell)
# #Re-order levels
# old.levels <- levels(all.Tcell$cluster)
# level.order <- c(1,3,6,8,9,15,13,10,14,2,4,18,19,16,5,11,12,17,7)
# all.Tcell$cluster <- factor(all.Tcell$cluster, levels = old.levels[level.order])
# all.Tcell$SCT_snn_res.1 <- factor(all.Tcell$SCT_snn_res.1, levels = levels(all.Tcell$SCT_snn_res.1)[level.order])
# DimPlot(all.Tcell, group.by = "cluster")
# DimPlot(all.Tcell, group.by = "SCT_snn_res.1")
```

## Generate UMAP plots

```{r}
## reorder patient levels
all.Tcell$orig.ident <- as.factor(all.Tcell$orig.ident)
old.levels <- levels(all.Tcell$orig.ident)
all.Tcell$orig.ident <- factor(all.Tcell$orig.ident, levels =  old.levels[c(1,5:9,14, 2:4, 10:13)])

#Subset to very few cells to get small pdfs (for vectorized legends)
cells <- WhichCells(all.Tcell)
cells.sub <- sample(cells, 100)
object <- subset(all.Tcell, cells = cells.sub)

object <- all.Tcell
  
umap_clustername<- DimPlot(object, group.by = "cluster")+
  theme_void()
umap_patient <- DimPlot(object, group.by = "orig.ident")+
  theme_void()
umap_TIG <- DimPlot(object, group.by = "TIG")+
  theme_void()
umap_clusternumber <- DimPlot(object, group.by = "SCT_snn_res.1", label=TRUE)+
  theme_void()
umap_metacluster <- DimPlot(object, group.by = "metacluster")+
  theme_void()

pdf(paste0(out.path, "Fig2_umap_small.pdf"), width = 20, height = 20)
p <- (umap_clustername | umap_clusternumber) / (umap_TIG | umap_patient)
dev.off()

png(paste0(out.path, "Fig2S_umap_patient.png"), width = 20, height = 16, units = "cm", res = 200)
umap_patient
dev.off()
```

## Cluster average heatmap of selected marker genes

```{r}
features_general = c("CD3E", "CD3G", "CD3D", "CD8A", "CD4", "CD69", "CD27")
TCR = c("TRAC", "TRBC1", "TRBC2", "TRDC", "TRGC1", "TRGC2")
features_Treg = c('CCR8', 'IL1RL1', 'IL2RA', 'IL1R2',  'TNFRSF8', 'TNFRSF4', 'TNFRSF9', 'TNFRSF18', 'CD177', 'CARD16', "BATF", "FOXP3", "CTLA4", "ICOS", "TIGIT")
features_Tnaive = c("CCR7", "IL7R", "CXCR4")
features_exhausted = c("PDCD1", "LAG3", "CTLA4", "HAVCR2", "ITGAE", "ENTPD1")
features_cytotoxic = c("CCL4", "CCL3", "CCL5", "TCF7","GZMA", "GZMB", "GZMH", "GZMK")
features_follicular <- c("CXCL13", "IGFL2", "NR3C1", "CD200", "CPM", "GNG4", "CHN1", "ITM2A", "CXCR5", "PDCD1", "ICOS", "BTLA", "SH2D1A", "CD40LG", "IL21", "CD200")
features_proliferating <- c("HIST1H4C", "MKI67", "TUBB", "STMN1", "TUBA1B")
features_Savas_CD4CD103 <- c("ALOX5AP", "PDCD1", "IL26", "CKLF", "IFNG", "ANKRD28", "DAPK2")
features_Savas_CD4ILR7 <- c("IL7R", "CD69", "DUSP1", "FOS", "JUN", "CD40LG")
features_Savas_RGCC <- c("RGCC", "YPEL5", "LMNA", "ANXA1", "CXCR4", "ZFP36", "CREM", "ZNF331")
NK <- c("KLRC1", "SELL", "KLRC1", "FCGR3A", "NKG7", "KLRC1", "KLRC1", "AREG", "GNLY", "PRF1")
NK_activated = c("FCGR3A", "CX3CR1")

all <- c(features_general, TCR, features_Treg, features_Tnaive, features_exhausted, features_cytotoxic, features_follicular, features_proliferating, features_Savas_RGCC, features_Savas_CD4ILR7, NK, NK_activated)
all <- unique(all)

features_short <- c("CD3E", "CD3G", "CD3D", "CD8A", "CD4", "CD69", "CD27", "TRAC", "TRBC1", "TRBC2", "TRDC", "TRGC1", "TRGC2", "FOXP3", 'CCR8', 'IL1RL1', 'IL2RA', 'IL1R2', 'CD177', 'TNFRSF8', 'TNFRSF4', 'TNFRSF9', 'TNFRSF18', "CCR7", "CXCL13", "IGFL2", "NR3C1", "CD200", "CPM", "GNG4", "CHN1", "ITM2A", "CXCR5", "PDCD1", "BTLA", "SH2D1A", "CD40LG", "IL21", "HIST1H4C", "MKI67", "TUBB", "STMN1", "NCAM1", "NCR1", "SELL", "KLRB1","KLRC1", "KLRD1", "FCGR3A", "AREG", "GNLY", "PRF1", "BATF", "IRF4", "TOX", "TCF7")

#Calculate cluster averages
Idents(all.Tcell) <- all.Tcell$cluster
cluster.averages.table <- AverageExpression(object = all.Tcell, return.seurat = FALSE, assays = "RNA")
RNA.average <- as.matrix(cluster.averages.table[[1]])
#Normalize between 0 and 1
RNA.average.norm <- apply(RNA.average, 1, function(x)(x-min(x))/(max(x)-min(x)))
RNA.average.znorm <- apply(RNA.average, 1, function(x)(x - mean(x)) / sd(x))

#just the heatmap
p = Heatmap(t(subset(RNA.average.norm, select=features_short)), show_row_names = TRUE, row_dend_side = "left", heatmap_legend_param = list(title = "Nomralized\nmean counts"), col=viridis(100), cluster_rows = FALSE, cluster_columns=FALSE, row_names_side = "left", column_names_side = "top", column_names_rot = 90, column_dend_side = "bottom")
```

## Cluster average heatmap of Top10 DE genes

```{r}
# using MAST
Idents(all.Tcell) <- all.Tcell$cluster
cluster.markers <- FindAllMarkers(object = all.Tcell, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use="MAST", verbose = TRUE)
write.csv(cluster.markers, file = paste0(in.path, "DE_clusternames_all_MAST.csv"), row.names = FALSE)
marker.genes <- cluster.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
write.csv(marker.genes, file = paste0(in.path, "DE_clusternames_all_MAST_Top10.csv"), row.names = TRUE)

all.marker.genes <- read.csv(file = paste0(in.path, "DE_clusternames_all_MAST.csv"))
marker.genes <- all.marker.genes %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)

features <- marker.genes$gene
features.cluster <- marker.genes[,6:7]
colnames(features.cluster) <- c('cluster_expressed', 'gene')
DEgenes <- as.character(features.cluster$gene)

col_split <- factor(c("Treg", "Tnaive", rep("cytotoxic",4), "exhausted", "Tfh", "Tfh", rep("mixed",4), "T-proliferating", "NKT", rep("NK",3), "NK_activated"))
col_split <- factor(col_split, levels = levels(col_split)[c(10,8,1,2,7,3,9,6,4,5)])


#just the heatmap
p = Heatmap(t(subset(RNA.average.norm, select=unique(DEgenes))), show_row_names = TRUE, row_dend_side = "left", heatmap_legend_param = list(title = "Nomralized\nmean counts"), col=viridis(100), cluster_rows = FALSE, cluster_columns=FALSE, row_names_side = "left", column_names_side = "top", column_names_rot = 90, column_dend_side = "bottom", row_names_gp = gpar(fontsize = 6), cluster_column_slices = FALSE, column_split = col_split)


#combined markers
gene_comb_order <- c(features_general, TCR, features_Treg, DEgenes[1:5], features_Tnaive, DEgenes[6:10], features_cytotoxic, DEgenes[11:30], features_exhausted, DEgenes[31:35], features_follicular, DEgenes[36:45], features_Savas_CD4ILR7, features_Savas_RGCC, DEgenes[46:65], features_proliferating, DEgenes[66:75], NK, DEgenes[76:90], NK_activated, DEgenes[91:95])
gene_comb_order <- unique(gene_comb_order)

gene_comb_wo_general <- c(features_Treg, DEgenes[1:5], features_Tnaive, DEgenes[6:10], features_cytotoxic, DEgenes[11:30], features_exhausted, DEgenes[31:35], features_follicular, DEgenes[36:45], features_Savas_CD4ILR7, features_Savas_RGCC, DEgenes[46:65], features_proliferating, DEgenes[66:75], NK, DEgenes[76:90], NK_activated, DEgenes[91:95])
gene_comb_wo_general <- unique(gene_comb_wo_general)
general <- c(features_general, TCR)
gene_comb_wo_general <- setdiff(gene_comb_wo_general, general)

p = Heatmap(t(subset(RNA.average.norm, select=features_short)), show_row_names = TRUE, row_dend_side = "left", heatmap_legend_param = list(title = "Normalized\nmean counts"), col=viridis(100), cluster_rows = FALSE, cluster_columns=FALSE, row_names_side = "left", column_names_side = "top", column_names_rot = 90, column_dend_side = "bottom", row_names_gp = gpar(fontsize = 6), cluster_column_slices = FALSE, column_split = col_split)

```

## Cluster frequency by sample, by TIG & by pre-treatment status

```{r}
#Sample composition
sample.comp <- as.data.frame(prop.table(x=table(all.Tcell$cluster, all.Tcell$orig.ident), margin=2))
p_sample_comp = ggplot(sample.comp, aes(Var2, y = Freq, fill=Var1)) +
  geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(), axis.title.y = element_blank())+
  coord_flip()+
  theme(panel.background = element_blank())+
  ggtitle('Sample composition (T/NK clusters)')

#Cluster composition (relative)
cluster.comp <- as.data.frame(prop.table(x=table(all.Tcell$orig.ident, all.Tcell$cluster), margin=2))
p_cluster_comp = ggplot(cluster.comp, aes(Var2, y = Freq, fill=Var1)) +
  geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(), axis.title.y = element_blank())+
  coord_flip()+
  theme(panel.background = element_blank())+
  ggtitle('Cluster composition (by patient sample)')

#Cluster composition (absolute)
cluster.comp.abs <- as.data.frame(table(all.Tcell$cluster, all.Tcell$orig.ident))
p_cluster_comp_abs = ggplot(cluster.comp.abs, aes(Var1, y = Freq, fill=Var2)) +
  geom_bar(stat="identity")+
  theme(axis.title.x=element_blank(), axis.title.y = element_blank())+
  theme(panel.background = element_blank(), axis.text.x=element_text(angle=45, hjust=1))+
  ggtitle('Cluster composition (by patient sample)')

pdf(paste0(out.path, "Fig2S_cluster_sample_comp.pdf"), width = 8, height = 12)
p_sample_comp / p_cluster_comp_abs
dev.off()


### Cluster frequencies by TIG ###
colnames(sample.comp) <- c("cluster", "sample", "proportion")
sample.comp$TIG <- ifelse(sample.comp$sample == "TBB129" | sample.comp$sample  == "TBB171" | sample.comp$sample  == "TBB111" | sample.comp$sample  == "TBB165" | sample.comp$sample  == "TBB338" | sample.comp$sample  == "TBB184" | sample.comp$sample  == "TBB011", "TIG2", "TIG3")

# Calculate Wilcoxon Test
tdat <- as.data.table(sample.comp)
tdat$cluster <- as.factor(tdat$cluster)
tdat$TIG <- as.factor(tdat$TIG)
tdat$sample <- as.factor(tdat$sample)
pvalues <- tdat %>% 
  group_by(cluster) %>% 
  summarise(p=wilcox.test(proportion~TIG)$p.value)
tdat <- merge(tdat, pvalues, by.x = "cluster", by.y ="cluster", all.x = TRUE)
tdat$p.wt <- paste0('p=',round(tdat$p, digits=3))

#Boxplots
p = ggplot(tdat, aes(x= TIG, y = proportion, fill=TIG))+
  geom_boxplot()+
  geom_point(size = 2, pch=21, color = "black")+
  facet_wrap(~cluster+p.wt, scales="fixed", ncol=10, strip.position="bottom")+
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        strip.background = element_blank(),
        legend.background = element_blank())+
  ylab("Of total T/NK cells [%]")+
  xlab("cluster")

pdf(paste0(out.path, "Fig2S_cluster_frequency_boxplots.pdf"), width = 14, height = 5)
p
dev.off()

#p-value dot plot
mean <- tdat %>% 
  group_by(cluster, TIG) %>% 
  summarise(mean = mean(proportion))
mean <- spread(mean, key = "TIG", value = "mean")
delta_mean <- mean %>% 
  group_by(cluster) %>% 
  summarise(delta = TIG2-TIG3)
pvalues$delta <- delta_mean$delta

pvalues$padj <- ifelse(pvalues$delta > 0, log10(pvalues$p), -log10(pvalues$p))
pvalues$TIG <- ifelse(pvalues$delta > 0, "TIG2", "TIG3")
pvalues$cluster <- fct_rev(pvalues$cluster)

p <- ggplot(pvalues, aes(padj, cluster))+
  geom_point(aes(color=TIG))+
  xlab("-log10(p)")+
  geom_vline(xintercept = log10(0.05), linetype="dashed")+
  geom_vline(xintercept = -log10(0.05), linetype="dashed")+
    theme(axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.background = element_blank())

pdf(paste0(out.path, "Fig2_cluster_frequency_p.pdf"), width = 4, height = 5)
p
dev.off()



### Cluster frequencies by NA treatment ###
sample.comp <- as.data.frame(prop.table(x=table(all.Tcell$cluster, all.Tcell$orig.ident), margin=2))
colnames(sample.comp) <- c("cluster", "sample", "proportion")
sample.comp$NA_treatment <- ifelse(sample.comp$sample  == "TBB171" | sample.comp$sample == "TBB165", "yes", "no")

# Calculate Wilcoxon Test
tdat <- as.data.table(sample.comp)
tdat$cluster <- as.factor(tdat$cluster)
tdat$TIG <- as.factor(tdat$TIG)
tdat$sample <- as.factor(tdat$sample)
pvalues <- tdat %>% 
  group_by(cluster) %>% 
  summarise(p=wilcox.test(proportion~NA_treatment)$p.value)
tdat <- merge(tdat, pvalues, by.x = "cluster", by.y ="cluster", all.x = TRUE)
tdat$p.wt <- paste0('p=',round(tdat$p, digits=3))

#Boxplots
p = ggplot(tdat, aes(x= NA_treatment, y = proportion, fill=NA_treatment))+
  geom_boxplot()+
  geom_point(size = 2, pch=21, color = "black")+
  facet_wrap(~cluster+p.wt, scales="fixed", ncol=10, strip.position="bottom")+
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        strip.background = element_blank(),
        legend.background = element_blank())+
  ylab("Of total T/NK cells [%]")+
  xlab("cluster")

pdf(paste0(out.path, "Fig2S_cluster_frequency_NAtreament_boxplots.pdf"), width = 14, height = 5)
p
dev.off()
```

### Cluster frequencies by grade

```{r cluster-freq-grade}
clinical_data <- read.csv("Y://Code/10x/10x_Run1_Run2_Pilot_comb/output/clinical_data.csv")
clinical_data$Patient_ID <- paste0("T", clinical_data$Patient_ID)

lowG <- clinical_data[clinical_data$Grade %in% c("G1", "G2"),]$Patient_ID
highG <- clinical_data[clinical_data$Grade %in% c("G3"),]$Patient_ID

sample.comp <- as.data.frame(prop.table(x=table(all.Tcell$cluster, all.Tcell$orig.ident), margin=2))
colnames(sample.comp) <- c("cluster", "sample", "proportion")
sample.comp$Grade <- ifelse(sample.comp$sample %in% lowG, "G1/G2", "G3")

# Wilcoxon test
tdat <- as.data.table(sample.comp)
tdat$cluster <- as.factor(tdat$cluster)
tdat$Grade <- as.factor(tdat$Grade)
tdat$sample <- as.factor(tdat$sample)
pvalues <- tdat %>% 
  group_by(cluster) %>% 
  summarise(p=wilcox.test(proportion~Grade)$p.value)
tdat <- merge(tdat, pvalues, by.x = "cluster", by.y ="cluster", all.x = TRUE)
tdat$p.wt <- paste0('p=',round(tdat$p, digits=3))

#Boxplots
p = ggplot(tdat, aes(x= Grade, y = proportion, fill=Grade))+
  geom_boxplot()+
  geom_point(size = 2, pch=21, color = "black")+
  facet_wrap(~cluster+p.wt, scales="fixed", ncol=10, strip.position="bottom")+
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        strip.background = element_blank(),
        legend.background = element_blank())+
  ylab("Of total T/NK cells [%]")+
  xlab("cluster")


#p-value dot plot
mean <- tdat %>% 
  group_by(cluster, Grade) %>% 
  summarise(mean = mean(proportion))
mean <- spread(mean, key = "Grade", value = "mean")
delta_mean <- mean %>% 
  group_by(cluster) %>% 
  summarise(delta = `G1/G2` - G3)
pvalues$delta <- delta_mean$delta

pvalues$padj <- ifelse(pvalues$delta > 0, log10(pvalues$p), -log10(pvalues$p))
pvalues$Grade <- ifelse(pvalues$delta > 0, "G1/G2", "G3")
pvalues$cluster <- fct_rev(pvalues$cluster)

p <- ggplot(pvalues, aes(padj, cluster))+
  geom_point(aes(color=Grade))+
  xlab("-log10(p)")+
  geom_vline(xintercept = log10(0.05), linetype="dashed")+
  geom_vline(xintercept = -log10(0.05), linetype="dashed")+
    theme(axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.background = element_blank())+
  xlim(-2,2)

```

## CD8/CD4 assignment

```{r}
Idents(all.Tcell) <- all.Tcell$metacluster
T.only <- subset(all.Tcell, idents = c("NKT", "NK_activated", "NK"), invert=TRUE)

Idents(T.only) <- T.only$cluster
cluster.averages <- AverageExpression(object = T.only, return.seurat = FALSE, assays = "RNA")[[1]]
CD8.CD4.df <- as.data.frame(t(cluster.averages[c("CD8A", "CD8B", "CD4"),]))
CD8.CD4.df$cluster <- rownames(CD8.CD4.df)
CD8.CD4.df <- mutate(CD8.CD4.df, ratio = (CD8A+CD8B)/2/CD4)
CD8.CD4.df$cluster <- factor(CD8.CD4.df$cluster, levels = CD8.CD4.df$cluster)

p <- ggplot(CD8.CD4.df, aes(cluster,ratio))+
  geom_point()+
  ylab("CD8/CD4 ratio")+
  theme(panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        axis.text.x = element_text(angle = 90, hjust=1))+
  geom_hline(yintercept = 10, linetype = "dashed")
```

## KLRC1 + CD3E coexpression

```{r}
KLRC1 <- WhichCells(all.Tcell, expression = KLRC1 > 0 & CD3E == 0)
KLRC1 <- data.frame(cells = KLRC1, CD3_NCAM = "KLRC1")

CD3E <- WhichCells(all.Tcell, expression = KLRC1 == 0 & CD3E > 0)
CD3E <- data.frame(cells = CD3E, CD3_NCAM = "CD3E")

double <- WhichCells(all.Tcell, expression = KLRC1 > 0 & CD3E > 0)
double <- data.frame(cells = double, CD3_NCAM = "double")

double_neg <- WhichCells(all.Tcell, expression = KLRC1 == 0 & CD3E == 0)
double_neg <- data.frame(cells = double_neg, CD3_NCAM = "double_neg")

KLRC1_CD3 <- as.data.frame(rbind(KLRC1, CD3E, double, double_neg))
KLRC1_CD3.ord <- left_join(data.frame(cells = colnames(all.Tcell)), KLRC1_CD3, by="cells")
all.Tcell$KLRC1_CD3 <- KLRC1_CD3.ord$CD3_NCAM

tb <- as.data.frame(t(prop.table(table(all.Tcell$KLRC1_CD3, all.Tcell$cluster), margin = 2)))
tb.sub <- tb[tb$Var2 != "double_neg",]

p <- ggplot(tb.sub, aes(fill=Var2, y=Freq, x=Var1)) +
  geom_bar(stat="identity", position = "dodge")+
  scale_fill_manual("Expression", values = c("CD3E" = "yellow3", "KLRC1" = "green4", "double" = "dodgerblue"))+
  ylab("Proportion")+
  theme(panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        axis.text.x = element_text(angle = 90, hjust=1, vjust=0.5),
        axis.title.x = element_blank())

pdf(paste0(out.path, "Fig2S_NKT_coexpression.pdf"), width = 6, height = 3)
p
dev.off()

```

